#!/bin/sh
example_input() {
  cat <<EOF

EOF
}

expected_output() {
  cat <<EOF

EOF
}

runhaskell main.hs < input/best-practices.md > output/actual.md

if diff output/{actual,expected}.md; then
  echo "PASSED"
else
  ksdiff output/{actual,expected}.md
fi
